# Generated by Django 2.2.7 on 2019-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('cash_inflow', models.BigIntegerField()),
                ('cash_outflow', models.BigIntegerField()),
                ('daily_transaction', models.BigIntegerField()),
                ('internal_branding_photo', models.ImageField(blank=True, upload_to='internal_branding')),
                ('external_branding_photo', models.ImageField(blank=True, upload_to='external_branding')),
                ('tariffs_display_photo', models.ImageField(blank=True, upload_to='tarrifs_photo')),
            ],
        ),
    ]
